version: "3.9"

services:
    server:
        build: ./backend
        # image: "blog-server:latest"
        container_name: blog-server
        ports:
            - 10000:10000
        environment:
            NODE_ENV: production
        env_file:
            - ./.env

    front:
        build: ./frontend
        # image: "blog-front:latest"
        container_name: blog-front
        ports:
            - 80:80
        depends_on:
            - server
        environment:
            NODE_ENV: production
